export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';


export const LOAD_CHECKOUT_SUCCESS='LOAD_CHECKOUT_SUCCESS';
export const SAVE_CHECKOUT_SUCCESS = 'SAVE_CHECKOUT_SUCCESS';

export const LOAD_COUNTRY_SUCCESS = 'LOAD_COUNTRY_SUCCESS';

export const REMOVE_PRODUCT_FROM_CHECKOUT_SUCCESS = 'REMOVE_PRODUCT_FROM_CHECKOUT_SUCCESS';


